### ISSUE TITLE
data formats 

### ISSUE THREAD

**Issue by annefou** [NordicESMhub/esm-python-tutorials#1]
Which data formats should we introduce in the course apart from netCDF?

**Comment by annefou** [comment]
data for the course can be stored in /projects/NS1000K/NEGI-Andoya

**Comment by daliagachc** [comment]
Maybe, we could also give a small intro on parsing the ubiquitous csv/text files? 
Do we know whats the python level of the students?

**Comment by sarambl** [comment]
Michael sent out a document with the applicants were they answer their prior knowledge in python:
13 regular users, 10 Programmed now and then with python, 3 Never used it, 1 Expert. (Roughly counted).
I think a small intro to csv/text files would be nice! But if we're not going to use that, then it might be just seeing it done and then forgetting it.. I guess some people manage to stay focused even if the immediate reward of the knowledge is not evident though.

**Comment by annefou** [comment]
Do we have relevant data in csv/txt format?

**Comment by sarambl** [comment]
As I entered this process a bit late I am not entirely sure I know what the plan is, but there seems to be an expectation that they will be able to work on their own data. I'm not sure how we would do this though if they are supposed to work in groups.
But! I checked the applicant list again and it seems that most people who wrote something on their own data are using data in hdf or netcdf (a lot of model output and some satellite stuff). In addition there are some people who have listed rain gauges, weather data (format not specified) or zeppelin data. No idea what the format would be, but I guess that might be where csv/text files come in.

**Comment by daliagachc** [comment]
I also checked the the applicant list and I agree that it looks mostly netCDF/hdf. Nobody has specified any other formats. So maybe we can focus on it. 
Do we have any updates on the teaching program? I'm also a little bit lost about the plan. Shall we have a skype meeting at some point?

**Comment by MichaelSchulzMETNO** [comment]
netcdf/hdf is great. There will be some ascii data as well and EBAS / Aeronet read routines Jonas has worked upon. The programme - I shall see into it today. However, it would be helpful if you jointly foresee  an introduction into github, ncview, cdo, nco, jupyter, iris, python librariries, nird facilities. Maybe you have other tools in mind. Students need to look into model files, and then start python workup. pyaerocom from Jonas can be used by one group, which Jonas can assist to. 

We can have a skype this afternoon any time. Shall we try at kl14 Oslo time?

**Comment by jgliss** [comment]
kl14 works well for me for a Skype meeting.

**Comment by annefou** [comment]
14:00 CEST time is OK for me too.

**Comment by daliagachc** [comment]
14:00 CEST works for me too

**Comment by MichaelSchulzMETNO** [comment]
if you sent me your skype names by email, I shall start the meeting...

**Comment by sarambl** [comment]
1400 CEST works

**Comment by daliagachc** [comment]
diego.aliaga
